### ISSUE TITLE
validar para que não se coloque datas futuras a data atual

### ISSUE THREAD

**Issue by cbbathaglini** [petcomputacaoufrgs/covid-system#11]
tanto em nascimento quanto na data de coleta
por enquanto qq um q entenda um pouco de html pode ir lá e mudar na mão

**Comment by cbbathaglini** [comment]
essas validação tem q ser feita na regra de negócio correspondente

**Comment by brunoczim** [comment]
A validação já é feita me JS?

**Comment by cbbathaglini** [comment]
não, no fim eu e o thiago tentamos, mas nao funcionou ai eu descobri que da pra comparar as datas.
Olha a pasta utils e vai em Utils.php na função: public static function validarData($dataPassada,$objExcecao). Ficou barbada ahueaueha
