### ISSUE TITLE
Cadastro de pacientes - mensagem de cadastro com sucesso v.22abr2020

### ISSUE THREAD

**Issue by joao-netto** [petcomputacaoufrgs/covid-system#19]
Na mensagem de cadastro com sucesso pode aparecer o código da amostra. O usuário pode querer saber.

**Comment by cbbathaglini** [comment]
feito 
(https://user-images.githubusercontent.com/29007904/79996610-06f30100-848f-11ea-9396-2527aec94d8e.png)
