### ISSUE TITLE
Cadastro de amostras - caso de erro de cadastro - v22abr2020

### ISSUE THREAD

**Issue by joao-netto** [petcomputacaoufrgs/covid-system#20]
Quando dá um erro de cadastro (cadastro não é realizado) da amostra, o retorno perde algumas informações já inseridas: Perfil, CEP e município. É bom manter, para não ter que colocar novamente, ou gerar outra mensagem de erro (o usuário pensa que já preencheu e daí dá novo erro).

**Comment by cbbathaglini** [comment]
feito
![image](https://user-images.githubusercontent.com/29007904/79999252-13c52400-8492-11ea-9873-a944ed05bce4.png)
![image](https://user-images.githubusercontent.com/29007904/79999314-22134000-8492-11ea-9c32-c9663e96fcf8.png)
