### ISSUE TITLE
Visualização do cadastro da amostra - v22abr2020

### ISSUE THREAD

**Issue by joao-netto** [petcomputacaoufrgs/covid-system#21]
Na lista de amostras ao clicar no botão que tem o lápis vem os dados da amostra:
- Não aprece o perfil, o CEP e as observações anotadas.
- Não tem botão de atualização (salvar ou algo assim). Se o objetivo é só visualizar, ok, Mas tem que ter uma forma de corrigir infos no cadastro.

**Comment by joao-netto** [comment]
O usuário administrador pode apagar o registro da amostras, mas não consegue editar.
É interessante que usuários administradores e quem inseriu a amostra possa editar.

**Comment by cbbathaglini** [comment]
feito
![image](https://user-images.githubusercontent.com/29007904/80020629-bcce4780-84af-11ea-8c61-6667acd0d792.png)
