### ISSUE TITLE
Páginas Estão Meio Lentas Mesmo Localmente

### ISSUE THREAD

**Issue by brunoczim** [petcomputacaoufrgs/covid-system#3]
Até agora sei da index.php, mas acho que tem outras

**Comment by cbbathaglini** [comment]
ta abrindo em qual navegador? eu abria sempre no firefox e ficava MEGA lento, ai no chrome tava normal .. pelo que eu vi era esse link: https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js 
que travava

**Comment by brunoczim** [comment]
Então, eu tava no firefox mesmo. Eu fiz algumas coisas pra arrumar isso:
* Eu troquei o ícone por um menor (aquele ícone era mais de 1MiB)
* Eu baixei as dependências
