### ISSUE TITLE
Erro Ao Tentar Logar

### ISSUE THREAD

**Issue by brunoczim** [petcomputacaoufrgs/covid-system#4]
Encontro esse erro ao tentar logar:
```
erro na sessão
```
Forçando o PHP a me dizer o erro, na classe Session, encontro isso:
```
Exception: Table 'amostras_covid19.tb_rel_usuario_perfilUsuario' doesn't exist in /home/bruno/prog/php/covid-system/classes/Banco/Banco.php:124
Stack trace:
#0 /home/bruno/prog/php/covid-system/classes/Rel_usuario_perfilUsuario/Rel_usuario_perfilUsuario_BD.php(71): Banco->consultarSql()
#1 /home/bruno/prog/php/covid-system/classes/Rel_usuario_perfilUsuario/Rel_usuario_perfilUsuario_RN.php(91): Rel_usuario_perfilUsuario_BD->listar()
#2 /home/bruno/prog/php/covid-system/classes/Sessao/Sessao.php(60): Rel_usuario_perfilUsuario_RN->listar()
#3 /home/bruno/prog/php/covid-system/public_html/index.php(8): Sessao->logar()
#4 {main}
```

**Comment by cbbathaglini** [comment]
isso foi um problema q eu encontrei hj de manhã, o script passou o nome das tabelas com as letras todas minusculas, então tb_rel_usuario_perfilUsuario  tem que ser tb_rel_usuario_perfilusuario. o U tem q ser minúsculo.
na public function listar(PerfilUsuario $objPerfilUsuario, Banco $objBanco)  em perfilUsuarioBD o nome da tabela ta com o U maiusculo. mts desses erros eu arrumei no servidor q eu subi, mas ainda não arrumei noo meu código aqui
