### ISSUE TITLE
Codificação de Caractéres Bugada Em Cadastrar Amostra > Paciente SUS

### ISSUE THREAD

**Issue by brunoczim** [petcomputacaoufrgs/covid-system#5]
"Digite o nome da mÃ£e:"

![image](https://user-images.githubusercontent.com/18701450/79390136-8dff2100-7f45-11ea-93a4-1ab7908ffffc.png)

**Comment by cbbathaglini** [comment]
arrumei isso, é que quando subo pro servidor ele fica com os caracteres estranhos assim. Não sei por pq

**Comment by brunoczim** [comment]
Acho que arrumei no e7e3788

**Comment by joao-netto** [comment]
Isto tem a ver com o tipo de código que se usa para representar o texto e o que o navegador usa, se não for indicado explicitamente a codificação (UTF-x, etc...)
